apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-auth
  labels:
    app: hello-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-auth
  template:
    metadata:
      labels:
        app: hello-auth
        ghostkube.io/service: "auth-service"
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-auth-svc
spec:
  selector:
    app: hello-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP